{% set name = "refcount" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 88aefe6cdf7758aa94ac09979014bad2a0865dadb72bc8bb30c30e91ec9c27e7

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - cffi >=1.11.5
    - python >=3.6

test:
  imports:
    - refcount
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/csiro-hydroinformatics/pyrefcount
  summary: A Python package for reference counting and interop with native pointers
  description: |
    This package helps you achieve reliable management of memory 
    allocated in native libraries, written for instance in C++. While 
    it boils down to "simply" maintaining a set of counters, 
    it is deceptively complicated to do so properly and not end up 
    with memory leaks or crashes.
    <https://pyrefcount.readthedocs.io/en/latest/>.
  dev_url: https://github.com/csiro-hydroinformatics/pyrefcount
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - jmp75
